### ISSUE TITLE
Errors deploying buildpack on Bluemix

### ISSUE THREAD

**Issue by pankajdubeycanada** [LeoKotschenreuther/python-tesseract-buildpack#3]
What version of Cloud Foundry are you using?
v279

What version of the buildpack you are using?
1.5.8

If you were attempting to accomplish a task, what was it you were attempting to do?
Deploying buildpack on IBM Bluemix

What did you expect to happen?
I should be able to deploy Python application with this buildpack

What was the actual behavior?
I am getting this error:

Unpacking Tesseract-OCR binaries

tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'

tar: Ignoring unknown extended header keyword 'SCHILY.dev'

tar: Ignoring unknown extended header keyword 'SCHILY.ino'

tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

tar: Ignoring unknown extended header keyword 'SCHILY.dev'

tar: Ignoring unknown extended header keyword 'SCHILY.ino'

tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'

tar: Ignoring unknown extended header keyword 'SCHILY.dev'

tar: Ignoring unknown extended header keyword 'SCHILY.ino'

tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

tar: Ignoring unknown extended header keyword 'SCHILY.dev'

tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

bin/

tar: Ignoring unknown extended header keyword 'SCHILY.ino'

bin/tesseract

lib/

lib/libgif.so.4

tar: Ignoring unknown extended header keyword 'SCHILY.dev'

tar: Ignoring unknown extended header keyword 'SCHILY.ino'

tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

lib/libjpeg.so.62

tar: Ignoring unknown extended header keyword 'SCHILY.dev'

tar: Ignoring unknown extended header keyword 'SCHILY.ino'

tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

lib/libjpeg.so.8

tar: Ignoring unknown extended header keyword 'SCHILY.dev'

tar: Ignoring unknown extended header keyword 'SCHILY.ino'

tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

lib/liblept.so.4

lib/libpng.so

tar: Ignoring unknown extended header keyword 'SCHILY.dev'

tar: Ignoring unknown extended header keyword 'SCHILY.ino'

tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

lib/libtesseract.so.3

tar: Ignoring unknown extended header keyword 'SCHILY.dev'

tar: Ignoring unknown extended header keyword 'SCHILY.ino'

tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

tar: Ignoring unknown extended header keyword 'SCHILY.dev'

tar: Ignoring unknown extended header keyword 'SCHILY.ino'

tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

lib/libtiff.so.4

lib/libtiff.so.5

tar: Ignoring unknown extended header keyword 'SCHILY.dev'

tar: Ignoring unknown extended header keyword 'SCHILY.ino'

tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

tar: Ignoring unknown extended header keyword 'SCHILY.dev'

tar: Ignoring unknown extended header keyword 'SCHILY.ino'

tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

lib/libwebp.so.5

Getting Tesseract-OCR training data

eng training data

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  1596  100  1596    0     0  15753      0 --:--:-- --:--:-- --:--:-- 15960

gzip: stdin: not in gzip format

tar: Child returned status 1

Exit status 223

Staging failed: STG: Exited with status 223

Destroying container

tar: Error is not recoverable: exiting now

Failed to compile droplet: Failed to compile droplet: exit status 2

Stopping instance 6048037e-b517-4cbd-a5e9-d5f757889b13

Successfully destroyed container

FAILED

Error restarting application: BuildpackCompileFailed

Please confirm where necessary:
* [Yes ] I have included a log output 
* [ Yes] My log includes an error message 
* [ Yes] I have included steps for reproduction

**Comment by LeoKotschenreuther** [comment]
Hi Pankaj,

I just had a look at the code where the build pack tries to download the training data for tesseract.
It looks like the domain [https://tesseract-ocr.googlecode.com](https://tesseract-ocr.googlecode.com) doesn’t exist anymore, that’s where the build pack used to download the training data.

Unfortunately, there is nothing I can do about that.
If you find another server that hosts this training data, you could fix the build pack.

Have a look at the [code](https://github.com/LeoKotschenreuther/python-tesseract-buildpack/blob/master/bin/steps/tesseract#L26) where it tries to download the training data, it should be self explanatory how to replace the URL.

**Comment by pankajdubeycanada** [comment]
Hi Leo,
Thank you for responding. While doing a little search I found that the code has moved to github:
https://code.google.com/archive/redirect/a/code.google.com/p/tesseract-ocr?movedTo=https:%2F%2Fgithub.com%2Ftesseract-ocr

Could you please help me with replacing the url, I am pretty new to python and trying to figure things out.

Thank you in advance for your help.

Regards,
Pankaj Dubey

**Comment by LeoKotschenreuther** [comment]
That's actually not Python but a bash script.
The `curl` command downloads the file and the `tar` command unpacks the .tar.gz file. Have a look at [Bash programming](http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO.html#toc5) to learn how to use bash.

I just had a look at the tesseract-ocr GitHub and it also seems like they don't offer the training data as .tar.gz files anymore but the raw files instead. I don't remember anymore what was specifically inside the .tar.gz file, was it just one file like the [eng.traineddata](https://github.com/tesseract-ocr/tessdata/blob/master/eng.traineddata)?

If so, you could try to download it with curl and then to move it to the proper location. The code should look something like this:

```bash
curl $TRAINING_DATA_URL
mv $TRAINING_DATA_FILE $INSTALL_DIR_TRAINING_DATA/
```

**Comment by pankajdubeycanada** [comment]
I found the link where the training files are available: https://sourceforge.net/projects/tesseract-ocr-alt/files/tesseract-ocr-3.02.eng.tar.gz
But I still get this error when I updated the the link in the code:

Getting Tesseract-OCR training data
eng training data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   443  100   443    0     0   1889      0 --:--:-- --:--:-- --:--:--  1977
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to compile droplet: Failed to compile droplet: exit status 2
Exit status 223

**Comment by LeoKotschenreuther** [comment]
It looks like the source forge link is not the actual link to the file. I followed the link forwarding and was able to download the actual file from [here](https://newcontinuum.dl.sourceforge.net/project/tesseract-ocr-alt/tesseract-ocr-3.02.eng.tar.gz). I will update the code.

**Comment by LeoKotschenreuther** [comment]
Should be fixed now. Reopen the issue if not.

**Comment by pankajdubeycanada** [comment]
Thank you Leo 😀
